#____________________________________________________________________________________________
# servoj
# 
#____________________________________________________________________________________________

float64[6] pos               # position  
float64[6] vel               # velocity
float64[6] acc               # acceleration
float64    time              # time
int8       mode              # Theo : to do : refine comments ;servoj mode 0:DR_SERVO_OVERRIDE, 1:DR_SERVO_QUEUE